version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-app:latest
    container_name: my-app
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    environment:
      - RAILS_ENV=production
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    volumes:
      - ".:/rails"
      - "rails_cache:/usr/local/bundle"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:13
    container_name: my-app-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp_production
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: my-app-redis
    networks:
      - app_network

volumes:
  rails_cache:
  postgres_data:

networks:
  app_network:
    driver: bridge
