# name: "${PROJECT_NAME}-development"

services:
  nginx_proxy:
    image: nginx
    hostname: nginx_proxy
    container_name: "${PROJECT_NAME}-nginx_proxy"
    ports:
      - $HTTP_PORT:80
    volumes:
      - $PWD/.docker/nginx/proxy.development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - phpmyadmin
      - web
  # Dịch vụ web (Rails app)
  web:
    build: .
    volumes:
      - ".:/app"  # Mount thư mục hiện tại của bạn vào container
    ports:
      - "3000:3000"  # Mở cổng 3000 cho ứng dụng Rails      
    depends_on:
      - ruby_database  # Đảm bảo web service chạy sau db service
    environment:
      - RAILS_ENV=development
      - DATABASE_USERNAME=$SQL_DATABASE_USER
      - DATABASE_PASSWORD=$SQL_DATABASE_PASSWORD
      - DATABASE_NAME=$SQL_DATABASE_NAME
      - DATABASE_HOST=$DOCKER_SQL_HOST
      - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - AWS_REGION=$AWS_REGION
      - AWS_BUCKET=$AWS_BUCKET
      - SHIPPIT_BASE_URL=$SHIPPIT_BASE_URL
      - SHIPPIT_API_KEY=$SHIPPIT_API_KEY
      - ADDRESS_FINDER_KEY=$ADDRESS_FINDER_KEY
      - ADDRESS_FINDER_SECRET=$ADDRESS_FINDER_SECRET
      - MAIL_SMTP_USER=$MAIL_SMTP_USER
      - MAIL_SMTP_PASS=$MAIL_SMTP_PASS
      - MAIL_SMTP_PORT=$MAIL_SMTP_PORT
      - MAIL_SMTP_HOST=$MAIL_SMTP_HOST
      - MAIL_SMTP_FROM=$MAIL_SMTP_FROM
      - MAIL_SMTP_DOMAIN=$MAIL_SMTP_DOMAIN
      - CONTACT_FORM_RECIPIENT=$CONTACT_FORM_RECIPIENT

  # ruby_server:
  #   hostname: ruby_server
  #   container_name: "${PROJECT_NAME}-ruby_server"
  #   user: $UID
  #   build:
  #     context: $PWD/.docker/docker/ruby
  #     dockerfile: Development.Dockerfile
  #     args:
  #       - WORKING_DIR=$DOCKER_WORKING_DIR
  #   working_dir: $DOCKER_WORKING_DIR    
  #   volumes:
  #     - $PWD/storefront:$DOCKER_WORKING_DIR
  #   depends_on:
  #     - ruby_database
  #   environment:
  #     - DATABASE_USERNAME=$SQL_DATABASE_USER
  #     - DATABASE_PASSWORD=$SQL_DATABASE_PASSWORD
  #     - DATABASE_NAME=$SQL_DATABASE_NAME
  #     - DATABASE_HOST=$DOCKER_SQL_HOST
  #     - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
  #     - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
  #     - AWS_REGION=$AWS_REGION
  #     - AWS_BUCKET=$AWS_BUCKET
  #     - SHIPPIT_BASE_URL=$SHIPPIT_BASE_URL
  #     - SHIPPIT_API_KEY=$SHIPPIT_API_KEY
  #     - ADDRESS_FINDER_KEY=$ADDRESS_FINDER_KEY
  #     - ADDRESS_FINDER_SECRET=$ADDRESS_FINDER_SECRET
  #     - MAIL_SMTP_USER=$MAIL_SMTP_USER
  #     - MAIL_SMTP_PASS=$MAIL_SMTP_PASS
  #     - MAIL_SMTP_PORT=$MAIL_SMTP_PORT
  #     - MAIL_SMTP_HOST=$MAIL_SMTP_HOST
  #     - MAIL_SMTP_FROM=$MAIL_SMTP_FROM
  #     - MAIL_SMTP_DOMAIN=$MAIL_SMTP_DOMAIN
  #     - CONTACT_FORM_RECIPIENT=$CONTACT_FORM_RECIPIENT

  ruby_database:
    hostname: ruby_database
    container_name: "${PROJECT_NAME}-ruby_database"
    image: mysql:8.0.40
    environment:
      - MYSQL_ROOT_PASSWORD=$SQL_DATABASE_ROOT_PASSWORD
      - MYSQL_DATABASE=$SQL_DATABASE_NAME
      - MYSQL_USER=$SQL_DATABASE_USER
      - MYSQL_PASSWORD=$SQL_DATABASE_PASSWORD
    volumes:
      - $PWD/.docker/schema/:/docker-entrypoint-initdb.d
      - $PWD/.docker/mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - 33063:3306

  # phpmyadmin:
  #   hostname: phpmyadmin
  #   container_name: $PROJECT_NAME-phpmyadmin
  #   image: phpmyadmin/phpmyadmin:latest
  #   environment:
  #     - PMA_HOST=$DOCKER_SQL_HOST
  #     - PMA_PORT=$SQL_DATABASE_PORT
  #     - PMA_USER=$SQL_DATABASE_USER
  #     - PMA_PASSWORD=$SQL_DATABASE_PASSWORD
  #     - PMA_ABSOLUTE_URI=http://localhost/pma
  #   depends_on:
  #     - ruby_database
