version: '3.8'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    volumes:
      - ".:/my_spree_commerce"
    expose:
      - "3000"  # Chỉ mở port nội bộ cho container
    depends_on:
      - nginx

  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Mở port 80 cho nginx từ bên ngoài
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro  # Sao chép cấu hình nginx vào container
    depends_on:
      - web
