services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b '0.0.0.0'"
    volumes:
      - ".:/myapp"
    environment:
      DB_HOST: "db_host_address_or_ip"
      DB_PASSWORD: "your_db_password"
    expose:
      - "3000"  # Không cần phải mở cổng cho nginx, vì chỉ web service cần lắng nghe ở port 3000.
    
  nginx:
    image: nginx:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"  # Mở port 80 cho nginx từ bên ngoài
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
