default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: <%= ENV["DATABASE_HOST"] %>
  database: <%= ENV["DATABASE_NAME"] %>  
  # database: my_spree_commerce
  # username: user
  # password: password
  # host: 127.0.0.1
  # port: 33063
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
